name: .NET

on:
  workflow_dispatch:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: windows-2019

    steps:
    - uses: actions/checkout@v2

    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v1

    - name: Setup NuGet
      uses: NuGet/setup-nuget@v1.0.5
  
    - name: setup-msbuild
      uses: microsoft/setup-msbuild@v1.1

    - name: Restore Packages
      run: nuget restore BinDumper.sln

    - name: Build solution
      run: msbuild BinDumper.sln -t:rebuild -property:Configuration=Release
      
    - name: Upload
      uses: actions/upload-artifact@v3
      with:
          name: output
          path: ${{ github.workspace }}
